[default]
# specified so solc compiles legacy wyvern contracts using 0.4.13, for use with getCode cheatcode
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
#via_ir = true
fuzz_runs = 5000
fuzz_max_global_rejects = 10000000
src = 'contracts'
out = 'out'
libs = ['node_modules']
test = 'test/foundry'
remappings = [
    'ds-test=lib/ds-test/src/',
    'forge-std=lib/forge-std/src/',
]


# See more config options https://github.com/gakonst/foundry/tree/master/config