[default]
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
src = 'src'
out = 'out'
libs = ['src/lib', 'contracts/lib']
remappings = ['ds-test/=src/lib/ds-test/src/']

# See more config options https://github.com/gakonst/foundry/tree/master/config
