[default]
via_ir = true
src = 'contracts'
out = 'out'
libs = ['node_modules']
test = 'test/foundry'
remappings = [
    'ds-test=lib/ds-test/src/',
    'forge-std=lib/forge-std/src/',
]
fuzz_runs = 5000
fuzz_max_global_rejects = 500_000
fuzz_max_local_rejects = 10_000
optimizer_runs = 15000

[reference]
solc = '0.8.7'
via_ir = false
src = 'reference'
out = 'reference-out'
# specify something so it doesn't try to compile the 0.8.13 files in test/foundry
test = 'reference'

[optimized]
solc = '0.8.13'
out = 'optimized-out'

[test]
solc = '0.8.13'
via_ir = false
src = 'test/foundry'

[lite]
out = 'optimized-out'
via_ir = false
fuzz_runs = 1000

[local-ffi]
via_ir = false
fuzz_runs = 5000
src = 'reference'
out = 'reference-out'
ffi = true

# See more config options https://github.com/gakonst/foundry/tree/master/config
