[profile.default]
solc = '0.8.14'
via_ir = true
src = 'contracts'
out = 'out'
libs = ["node_modules", "lib"]
test = 'test/foundry'
remappings = [
    'ds-test=lib/ds-test/src/',
    'forge-std=lib/forge-std/src/',
    '@rari-capital/solmate/=lib/solmate/',
    'contracts/=contracts/',
    'murky/=lib/murky/src/',
]
fuzz_runs = 5000
fuzz_max_global_rejects = 2_000_000
optimizer_runs = 19_066
fs_permissions = [{ access = "read", path = "./optimized-out" }, { access = "read", path = "./reference-out" }]

[profile.reference]
solc = '0.8.7'
via_ir = false
src = 'reference'
out = 'reference-out'
# specify something so it doesn't try to compile the 0.8.14 files in test/foundry
test = 'reference'

[profile.optimized]
out = 'optimized-out'

[profile.test]
via_ir = false
src = 'test/foundry'

[profile.lite]
out = 'optimized-out'
via_ir = false
fuzz_runs = 1000

[profile.local]
via_ir = false
fuzz_runs = 1000
src = 'reference'
out = 'reference-out'

# See more config options https://github.com/gakonst/foundry/tree/master/config
